# lib/lettermint/generated/ is generated by the SDK generator and not formatted.
[
  inputs: [
    "mix.exs",
    ".formatter.exs",
    "lib/*.ex",
    "lib/lettermint/*.ex",
    "lib/lettermint/resources/*.ex",
    "test/**/*.{ex,exs}"
  ]
]
