#!/usr/bin/env bash
# Regenerates lib/lettermint/generated/ with the private SDK generator, or
# with --check verifies that the committed files are current.
#
# The generator is found at $LETTERMINT_SDK_GENERATOR (default ../sdk-generator).
# Without it (as in public CI), --check only verifies the generated headers.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/lib/lettermint/generated"
generator="${LETTERMINT_SDK_GENERATOR:-$root/../sdk-generator}"
check=""
case "${1:-}" in
  "") ;;
  --check) check="--check" ;;
  *) echo "Usage: scripts/generate.sh [--check]" >&2; exit 2 ;;
esac

if [[ -d "$generator/lettermint_sdkgen" ]]; then
  cd "$generator"
  python3 -m lettermint_sdkgen emit elixir --profile next --lock spec.next.lock.json --out "$out" $check
  exit 0
fi

if [[ -z "$check" ]]; then
  echo "The SDK generator was not found at $generator; set LETTERMINT_SDK_GENERATOR." >&2
  exit 1
fi

echo "The SDK generator is not available; checking the generated headers only." >&2
status=0
for file in types.ex operations.ex; do
  path="$out/$file"
  if [[ ! -f "$path" ]]; then
    echo "missing: $path" >&2; status=1; continue
  fi
  header="$(head -n 5 "$path")"
  if [[ "$(head -n 1 "$path")" != "# Generated by lettermint/sdk-generator — do not edit." ]] \
    || ! grep -q '^# Spec: lettermint/lettermint@[0-9a-f]\{40\}' <<<"$header" \
    || ! grep -q '^# sending-openapi.json SHA-256: [0-9a-f]\{64\}$' <<<"$header" \
    || ! grep -q '^# team-openapi.json SHA-256: [0-9a-f]\{64\}$' <<<"$header" \
    || ! grep -q '^# Naming profile: next$' <<<"$header"; then
    echo "invalid generated header: $path" >&2; status=1
  fi
done
[[ $status -eq 0 ]] && echo "generated headers ok"
exit $status
